name: PT-2
favicon: null
layout_spectrum: 0.7829925804398954
typography_spectrum: 0.48290949664078653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8104097342584282
  lightness: 0.8169692745432258
  saturation: 0.9318097913637757
  rhythmicContrast: 0.7315038740634918
purpose: []
