name: PT-2
favicon: null
layout_spectrum: 0.10629
typography_spectrum: 0.63703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#08b4c8'
    - '#8fc225'
    - '#89e1e6'
    - '#c9e591'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
